BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[ResetCode] (
    [id] BIGINT NOT NULL IDENTITY(1,1),
    [email] NVARCHAR(1000) NOT NULL,
    [token] NVARCHAR(1000) NOT NULL,
    [expires] DATETIME2 NOT NULL,
    CONSTRAINT [ResetCode_pkey] PRIMARY KEY CLUSTERED ([id]),
    CONSTRAINT [ResetCode_email_key] UNIQUE NONCLUSTERED ([email])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
